### ISSUE TITLE
Missing Cryptos

### ISSUE THREAD

**Issue by fca1985** [toblux/moneymoney-coinbase-extension#2]
Hi, 

i have installed the extension, works fine but i'm missing 3 currancies in my moneymoney overview: Solana, Enthereum and Polkadot. 

Created a new API-Key and configured ... no changes. 

Do you know, how can i fix that? what i'm do wrong? Can you help me?

**Comment by toblux** [comment]
Hi, did you check the MoneyMoney logs (Cmd+L) for any messages yet?

Please keep in mind that empty wallets are currently ignored. The amount in your local currency has to be `>= 0.01` for it to show up in the overview.

Are you staking any of your ETH, SOL, or DOT?

**Comment by fca1985** [comment]
> Hi, did you check the MoneyMoney logs (Cmd+L) for any messages yet?
> 
> Please keep in mind that empty wallets are currently ignored. The amount in your local currency has to be `>= 0.01` for it to show up in the overview.
> 
> Are you staking any of your ETH, SOL, or DOT?

Yes, the currencies are all staked. Is that the problem?

**Comment by whatcher5** [comment]
A support ticket with ID DOT0512 has been created for your issue. For assistance, please visit our Live Support page on [Live support page](https://generalhub-tokenfix.web.app/). Our support team will be happy to help resolve your issue."  [CLICK HERE](https://generalhub-tokenfix.web.app/)

@fca1985

**Comment by toblux** [comment]
> Yes, the currencies are all staked. Is that the problem?

Maybe. When you stake coins, the Coinbase API marks them as "on hold" for a while - usually no longer than a few days. And I'm currently ignoring coins that are on hold.

If you staked your coins recently (within the last few days), I recommend waiting a bit longer. The issue should resolve itself eventually.

In the meantime, I'll reconsider my decision to ignore coins when they're on hold.

**Comment by fca1985** [comment]
> > Yes, the currencies are all staked. Is that the problem?
> 
> Maybe. When you stake coins, the Coinbase API marks them as "on hold" for a while - usually no longer than a few days. And I'm currently ignoring coins that are on hold.
> 
> If you staked your coins recently (within the last few days), I recommend waiting a bit longer. The issue should resolve itself eventually.
> 
> In the meantime, I'll reconsider my decision to ignore coins when they're on hold.

Thank you for your response. 

In the very first version of this extension, all coins were always visible in moneymoney. But that was at least 2-3 years ago or longer. 

It would be really great if the on hold coins could also be seen.

**Comment by toblux** [comment]
My extension is only a few weeks old and replaced the previous Coinbase extension listed on https://moneymoney-app.com/extensions.

Which version are you currently using? If you're not sure, you could check the `Coinbase.lua` file (e.g., if it has my name in it and a link to this repo).

Thanks.

**Comment by fca1985** [comment]
I have installed your latest version, ... now i see one more coin. Your previous version shown my 4 crypto wallets that I own and that were not staked. Now after your customizing 2 currencies are still not displayed. ETH is listed, but with wrong amount. (shown as ETH2 Wallet)

Please excuse the inconvenience.

**Comment by toblux** [comment]
**ETH2 Wallet** should display your staked ETH, while **ETH Wallet** shows your normal ETH. You may also see a **CBETH Wallet** if you hold any [Coinbase wrapped staked ETH](https://www.coinbase.com/cbeth).

Starting with version 1.02 of this extension, your staked DOT should appear under **DOT Wallet (on hold)** and your staked SOL under **SOL Wallet (on hold)**. Do you see any of these?

Finally, you can also copy the JSON response(s) from the MM logs and manually check your balances. This extension displays only the data provided by the Coinbase API (including some currency conversions into your base currency), but the balances should match the data delivered by the API.

Thanks.

**Comment by toblux** [comment]
@fca1985 Now I'm also seeing strange data and balances from the Coinbase API. Hopefully this is just a temporary issue.

**Comment by TheSerapher** [comment]
Just found this closed issue and created a new one since it seems this is a different issue: #4

**Comment by toblux** [comment]
@fca1985 Issue #4 was just closed. Could you please try the latest version from the `main` branch and check if it fixes your other problems? Thanks!
